require('dotenv').config()
const express = require('express')
const cookieParser = require('cookie-parser')
const compression = require('compression')
const authRoute = require('./routes/auth')
const callbackRoute = require('./routes/callback')
const refreshRoute = require('./routes/refresh')
const app = express()
const port = process.env.PORT || 7768
app.use((req, res, next) => {
  res.header('Access-Control-Allow-Origin', '*')
  res.header('Access-Control-Allow-Headers', 'Origin, X-Requested-With, Content-Type, Accept')
  next()
})
app.use(cookieParser())
app.use(compression())
app.use('/auth', authRoute)
app.use('/callback', callbackRoute)
app.use('/refresh', refreshRoute)
app.listen(port, () => console.log('Listening on port ' + port))